language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

script: gulp travis

before_script:
  - npm install -g @angular/cli

script:
  - ng lint

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN ae938890f60f0e127ddc171c5bf615f035d6193a
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change