language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

script: gulp travis

before_script:
  - npm install -g @angular/cli

script:
  - ng lint

after_failure:
  - git reset --hard HEAD~1
  - git push -f origin master

after_success:
  - git commit -am "auto commit"
  - git push -u origin master

notifications:
  email:
    on_failure: change
    on_success: change