language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

script: gulp travis

before_script:
  - npm install -g @angular/cli

script:
  - ng lint

after_success:
  github_token: $GITHUB_TOKEN
  on:
    branch: master
  - git reset --hard HEAD~1
  - git push -f origin master

notifications:
  email:
    on_failure: change
    on_success: change