language: node_js
node_js:
  - "stable"

branches:
  only:
    - master

before_install:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" >> ~/.netrc

script: gulp travis

before_script:
  - npm install -g @angular/cli

script:
  - ng lint

after_fail:
  - git reset --hard HEAD~1
  - git push -f origin master